// End-to-end Base Sepolia setup:
//   1. Generate 1 funded user EOA + 1 recipient EOA via viem.
//   2. Write everything to .env.
//
// NOTE: We do NOT deploy USDC — Base Sepolia has canonical Circle USDC at
// 0x036CbD53842c5426634e7929541eC2318f3dCF7e. After this script finishes you
// must manually fund USER_ADDRESS with testnet ETH (for gas) and USDC.
//
// Run: npm run gen

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import * as fs from "node:fs";
import * as path from "node:path";

const ENV_PATH = path.resolve(__dirname, "..", ".env");
const FACILITATOR_URL = process.env.FACILITATOR_URL ?? "http://localhost:4021";
const NETWORK = "base:sepolia";
const BASE_RPC_URL = "https://sepolia.base.org";
const USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e";

async function main() {
  console.log("━━━ elsax402-sessions test setup ━━━\n");

  // ── 1. Generate keypairs ─────────────────────────────────────────
  console.log("[1/2] Generating keypairs...");
  const userPk = generatePrivateKey();
  const recipientPk = generatePrivateKey();
  const user = privateKeyToAccount(userPk);
  const recipient = privateKeyToAccount(recipientPk);

  console.log(`    user:      ${user.address}`);
  console.log(`    recipient: ${recipient.address}`);

  // ── 2. Write .env ────────────────────────────────────────────────
  console.log("\n[2/2] Writing .env...");
  const lines: string[] = [
    `# Generated by scripts/generate-user.ts on ${new Date().toISOString()}`,
    `# Network: Base Sepolia. Regenerate with: npm run gen`,
    ``,
    `FACILITATOR_URL=${FACILITATOR_URL}`,
    `NETWORK=${NETWORK}`,
    `BASE_RPC_URL=${BASE_RPC_URL}`,
    ``,
    `# Canonical Circle USDC on Base Sepolia (6 decimals)`,
    `USDC_ADDRESS=${USDC_ADDRESS}`,
    ``,
    `# User (payer) — will sign the ERC20 approve tx. MUST BE FUNDED MANUALLY.`,
    `USER_PRIVATE_KEY=${userPk}`,
    `USER_ADDRESS=${user.address}`,
    ``,
    `# Recipient (resource server wallet) — receives transferFrom funds.`,
    `RECIPIENT_PRIVATE_KEY=${recipientPk}`,
    `RECIPIENT_ADDRESS=${recipient.address}`,
    ``,
  ];

  fs.writeFileSync(ENV_PATH, lines.join("\n"));
  console.log(`    ✓ Wrote ${ENV_PATH}`);

  // ── Instructions ──────────────────────────────────────────────────
  console.log("\n━━━ MANUAL FUNDING REQUIRED ━━━");
  console.log(
    `\nFund USER_ADDRESS with Base Sepolia ETH (https://www.alchemy.com/faucets/base-sepolia)`,
  );
  console.log(`and USDC (https://faucet.circle.com — select Base Sepolia).`);
  console.log(`\n    USER_ADDRESS: ${user.address}`);
  console.log(`\nThe recipient does NOT need to be funded — it only receives USDC.`);

  console.log("\nNext:");
  console.log("  1. Fund USER_ADDRESS via the faucets above (both ETH + USDC).");
  console.log("  2. cd ../x402-session-facilitator && npm run dev   (in another terminal)");
  console.log("  3. npm run status                                   (verify reachable + balances)");
  console.log("  4. npm run dry-run                                  (full end-to-end flow)");
}

main().catch((err) => {
  console.error("\n✗ setup failed:");
  console.error(err);
  process.exit(1);
});
